# Generated by Django 5.2.7 on 2025-10-27 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='WebFlare', max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('project_satisfaction', models.BooleanField(default=False)),
                ('portfolio_permission', models.BooleanField(default=False)),
                ('testimonial_opt_in', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('testimonial_text', models.TextField(blank=True)),
                ('signer_name', models.CharField(blank=True, max_length=255)),
                ('signer_title', models.CharField(blank=True, max_length=255)),
                ('signer_date', models.DateField(blank=True, null=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
