# Generated by Django 5.2.7 on 2025-10-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signoff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signoff',
            name='pdf_copy',
            field=models.FileField(blank=True, null=True, upload_to='signed_forms/'),
        ),
    ]
