# Generated by Django 5.2.7 on 2025-10-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signoff', '0002_signoff_pdf_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='signoff',
            name='interested_blog',
            field=models.BooleanField(default=False, verbose_name='Blog/News section'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='interested_booking',
            field=models.BooleanField(default=False, verbose_name='Booking system'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='interested_ecommerce',
            field=models.BooleanField(default=False, verbose_name='E-commerce setup'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='interested_email',
            field=models.BooleanField(default=False, verbose_name='Email setup'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='interested_extra_pages',
            field=models.BooleanField(default=False, verbose_name='Extra pages'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='interested_gallery',
            field=models.BooleanField(default=False, verbose_name='Gallery/Portfolio page'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='interested_maintenance',
            field=models.BooleanField(default=False, verbose_name='Hosting & maintenance'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='interested_seo',
            field=models.BooleanField(default=False, verbose_name='SEO setup'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='interested_social',
            field=models.BooleanField(default=False, verbose_name='Social feed integration'),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='portfolio_permission',
            field=models.BooleanField(default=False, help_text='Permission to use the project in portfolio and marketing materials'),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='project_satisfaction',
            field=models.BooleanField(default=False, help_text='Confirmation that all services have been completed satisfactorily'),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='testimonial_opt_in',
            field=models.BooleanField(default=False, help_text='Optional: Provide a testimonial for our services'),
        ),
    ]
