# Generated by Django 5.2.7 on 2025-10-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signoff', '0003_signoff_interested_blog_signoff_interested_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signoff',
            name='blog_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Blog/News price'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='booking_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Booking system price'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='ecommerce_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='E-commerce price'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='email_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Email setup price'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='extra_pages_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Extra pages price'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='gallery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gallery/Portfolio price'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='maintenance_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Hosting & maintenance price'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='seo_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='SEO setup price'),
        ),
        migrations.AddField(
            model_name='signoff',
            name='social_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Social feed price'),
        ),
    ]
