# Generated by Django 5.2.7 on 2025-10-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signoff', '0004_signoff_blog_price_signoff_booking_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signoff',
            name='provider',
            field=models.CharField(default='WebFlare (Daniel Picciau)', max_length=255),
        ),
    ]
